version: '3'
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./db/volumes:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: password
      DB_HOST_NAME: db

  web:
    build:
      context: . 
    command: /app/bin/bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      MYSQL_ROOT_PASSWORD: password
      DB_HOST_NAME: db
      RAILS_ENV: development
    depends_on:
      - db

